// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mY0yxv4UTiXEKI3kjAV0qx_iI-2Dd_4',
    appId: '1:861923833540:web:3f7438b36f125dc37a3b91',
    messagingSenderId: '861923833540',
    projectId: 'exercise8-7605b',
    authDomain: 'exercise8-7605b.firebaseapp.com',
    storageBucket: 'exercise8-7605b.firebasestorage.app',
    measurementId: 'G-EG0N01WZ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJS4pQ6aMxo_gru7Dj_F5XgWkNDi4u4eo',
    appId: '1:861923833540:android:a17308760b7ce55d7a3b91',
    messagingSenderId: '861923833540',
    projectId: 'exercise8-7605b',
    storageBucket: 'exercise8-7605b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCut9eS8Yjfbk--aORUQpZ7_KpiW4jlGHA',
    appId: '1:861923833540:ios:d57b005b7f87fa2e7a3b91',
    messagingSenderId: '861923833540',
    projectId: 'exercise8-7605b',
    storageBucket: 'exercise8-7605b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCut9eS8Yjfbk--aORUQpZ7_KpiW4jlGHA',
    appId: '1:861923833540:ios:d57b005b7f87fa2e7a3b91',
    messagingSenderId: '861923833540',
    projectId: 'exercise8-7605b',
    storageBucket: 'exercise8-7605b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7mY0yxv4UTiXEKI3kjAV0qx_iI-2Dd_4',
    appId: '1:861923833540:web:ba200b3430622e0e7a3b91',
    messagingSenderId: '861923833540',
    projectId: 'exercise8-7605b',
    authDomain: 'exercise8-7605b.firebaseapp.com',
    storageBucket: 'exercise8-7605b.firebasestorage.app',
    measurementId: 'G-1PB9T2M527',
  );
}
